name: CI/CD Pipeline to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./fitness-tracker-frontend  # ✅ Fixed indentation

      - name: Run Tests
        run: npm test
        working-directory: ./fitness-tracker-frontend  # ✅ Fixed indentation

      - name: Lint Code
        run: npm run lint || true  # Prevents failure due to linting errors
        working-directory: ./fitness-tracker-frontend  # ✅ Fixed indentation

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check AWS CLI Version
        run: aws --version  # ✅ Verify if AWS CLI is already installed

      - name: Update AWS CLI if necessary
        run: |
          if ! aws --version; then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install --update  # ✅ Use --update flag if CLI is already installed
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Deploy to Elastic Beanstalk
        run: |
          VERSION_LABEL=$(date +%Y%m%d%H%M%S)  # Generates a unique version label
          echo "Deploying with version label: $VERSION_LABEL"
          aws elasticbeanstalk create-application-version --application-name FitnessTrackerApp-ash83 --version-label $VERSION_LABEL --source-bundle S3Bucket="fitness-tracker-app-ash83",S3Key="deploy.zip"
          aws elasticbeanstalk update-environment --environment-name FitnessTrackerApp-env --version-label $VERSION_LABEL