name: CI/CD Pipeline to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Lint Code
        run: npm run lint || true  # Prevents failure due to linting errors

  deploy:
    name: Deploy to AWS Elastic Beanstalk
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Deploy to Elastic Beanstalk
        run: |
          zip -r deploy.zip . -x "*.git*"
          aws s3 cp deploy.zip s3://fitness-tracker-app/
          aws elasticbeanstalk create-application-version --application-name FitnessTrackerApp --version-label v1 --source-bundle S3Bucket="fitness-tracker-app",S3Key="deploy.zip"
          aws elasticbeanstalk update-environment --environment-name FitnessTrackerApp-env --version-label v1
